# Tasks File

- name: Install CRI-Dockerd
  ansible.builtin.apt:
    deb: https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.11/cri-dockerd_0.3.11.3-0.ubuntu-jammy_amd64.deb

- name: Enable CRI-Dockerd
  ansible.builtin.service:
    name: cri-docker
    enabled: true
    state: started
