Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|

    N = 4
    (1..N).each do |machine_id|
        config.vm.define "machine#{machine_id}" do |machine|
            machine.vm.hostname = "machine#{machine_id}"
            machine.vm.network "private_network", ip: "192.168.56.#{20+machine_id}"
            machine.vm.box = "generic/ubuntu2204"
        end     
    end
  #config.vm.define "master1" do |m1|
  #  m1.vm.box = "generic/ubuntu2204"
  #end

  #config.vm.provision "ansible" do |ansible|
  #  ansible.verbose = "v"
  #  ansible.playbook = "playbook.yml"
  #end
end