# Tasks File

# Install kubeadm, kubelet and kubectl
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present

- name: Add kubernetes signing key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
    force: true

- name: Add kubernetes repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version }}/deb/ /
    state: present
    update_cache: true

- name: Add Kubernetes apt preferences file to pin a version.
  ansible.builtin.template:
    src: apt-preferences-kubernetes.j2
    dest: /etc/apt/preferences.d/kubernetes
    mode: "0644"

- name: Install packages
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Ensure kubelet is enabled and started
  ansible.builtin.service:
    name: kubelet
    enabled: true
    state: started

- name: Check if Kubernetes has already been initialized.
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

# Initialize control plane
- name: Setup control plane
  ansible.builtin.include_tasks: control-plane.yml
  when: kubernetes_role == 'control_plane'

# Set up nodes.
- name: Get the kubeadm join command from the Kubernetes control plane.
  ansible.builtin.command: kubeadm token create --print-join-command
  changed_when: false
  when: kubernetes_role == 'control_plane'
  register: kubernetes_join_command_result

- name: Set the kubeadm join command globally.
  ansible.builtin.set_fact:
    kubernetes_join_command: >
      {{ kubernetes_join_command_result.stdout }}
      {{ kubernetes_join_command_extra_opts }}
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

- name: Setup Nodes
  ansible.builtin.include_tasks: node.yml
  when: kubernetes_role == 'node'
